export const PHASE_ONE_AUTHORITIES = {
    VIEW_APPLICANT: 'APP_VIEW_APPLICANT',
    ASSESS_APPLICANT: 'APP_ASSESS_APPLICANT',
    CREATE_ORGANIZATION: 'ORG_CREATE_ORGANIZATION',
    UPDATE_ORGANIZATION: 'ORG_UPDATE_ORGANIZATION',
    VIEW_ORGANIZATION: 'ORG_VIEW_ORGANIZATION',
    CREATE_REGISTRATION: 'REG_CREATE_REGISTRATION',
    VIEW_REGISTRATION: 'REG_VIEW_REGISTRATION',
    UPDATE_REGISTRATION: 'REG_UPDATE_REGISTRATION',
    ROUTE_REGISTRATION: 'REG_ROUTE_REGISTRATION',
    ASSESS_REGISTRATION: 'REG_ASSESS_REGISTRATION',
    CREATE_MIRF: 'MIR_CREATE_MIRF',
    UPDATE_MIRF: 'MIR_UPDATE_MIRF',
    VIEW_MIRF: 'MIR_VIEW_MIRF',
    DELETE_MIRF: 'MIR_DELETE_MIRF',
    UNLINK_MIRF: 'MIR_UNLINK_MIRF',
    CREATE_MARKET_TRADING_NODE: 'MTN_CREATE_MARKET_TRADING_NODE',
    VIEW_MARKET_TRADING_NODE: 'MTN_VIEW_MARKET_TRADING_NODE',
    UPDATE_MARKET_TRADING_NODE: 'MTN_UPDATE_MARKET_TRADING_NODE',
    MANAGE_DOCUMENTS: 'DOC_MANAGE_DOCUMENTS',
  
    VIEW_MQ: 'MQ_VIEW_METERING_QUANTITY',
    UPLOAD_BCQ: 'BCQ_UPLOAD_BILATERAL_CONTRACT_QUANTITY',
    VIEW_BCQ: 'BCQ_VIEW_BILATERAL_CONTRACT_QUANTITY',
    ASSESS_BCQ: 'BCQ_ASSESS_BILATERAL_CONTRACT_QUANTITY',
    CANCEL_BCQ: 'BCQ_CANCEL_BILATERAL_CONTRACT_QUANTITY',
    BCQ_CREATE_SPECIAL_EVENT: 'BCQ_CREATE_SPECIAL_EVENT',
    BCQ_VIEW_SPECIAL_EVENT: 'BCQ_VIEW_SPECIAL_EVENT',
    BCQ_EXPORT: 'BCQ_EXPORT',
    BCQ_VIEW_PROHIBITED: 'BCQ_VIEW_PROHIBITED',
    BCQ_ADD_PROHIBITED: 'BCQ_ADD_PROHIBITED',
    BCQ_DELETE_PROHIBITED: 'BCQ_DELETE_PROHIBITED',
    MQ_VIEW_METERING_QUANTITY: 'MQ_VIEW_METERING_QUANTITY',
  
    CREATE_ROLE: 'ADM_ROL_CREATE_ROLE',
    UPDATE_ROLE: 'ADM_ROL_UPDATE_ROLE',
    DELETE_ROLE: 'ADM_ROL_DELETE_ROLE',
    VIEW_ROLE: 'ADM_ROL_VIEW_ROLE',
    VIEW_PRIVILEGES: 'ADM_PRI_VIEW_PRIVILEGES',
    MANAGE_AUDIT_LOGS: 'ADM_AUD_MANAGE_AUDIT_LOGS',
    MANAGE_SYS_CONFIG: 'ADM_SYS_MANAGE_SYSTEM_CONFIG',
    MANAGE_JOB_SCHEDULER: 'ADM_JOB_MANAGE_JOB_SCHEDULER',
  
    MANAGE_MARKET_PARTICIPANTS:'ADM_MANAGE_MARKET_PARTICIPANTS',
    MANAGE_MARKET_OPERATORS: 'ADM_MANAGE_MARKET_OPERATORS',
    MANAGE_SYSTEM_OPERATORS: 'ADM_MANAGE_SYSTEM_OPERATORS',
  
    MANAGE_WESM_MARKET_PRODUCTS:'MP_MANAGE_WESM_MARKET_PRODUCTS',
    LINK_USER_REGISTRATION:'REG_LINK_USER_REGISTRATION',
    VIEW_LIST_OF_REGISTRATION:'REG_VIEW_LIST_OF_REGISTRATION',
  
    POSTREG_UPDATE_REGISTRATION: 'POSTREG_UPDATE_REGISTRATION',
    DEREGISTER_FACILITY: 'POSTREG_DEREGISTER_FACILITY',
    ADD_NEW_FACILITY: 'POSTREG_ADD_NEW_FACILITY',
    TRANSFER_FACILITY: 'POSTREG_TRANSFER_FACILITY',
    DEREGISTER_PARTICIPANT: 'POSTREG_DEREGISTER_PARTICIPANT',
    SUSPEND_PARTICIPANT: 'POSTREG_SUSPEND_PARTICIPANT',
    CEASE_PARTICIPANT: 'POSTREG_CEASE_PARTICIPANT',
    POSTREG_VIEW_LIST: 'POSTREG_VIEW_LIST',
  
    POSTREG_CREATE_USERACCOUNT: 'POSTREG_CREATE_USERACCOUNT',
    POSTREG_VIEW_LIST_USERACCOUNT: 'POSTREG_VIEW_LIST_USERACCOUNT',
    POSTREG_VIEW_USERACCOUNT_DETAILS: 'POSTREG_VIEW_USERACCOUNT_DETAILS',
    POSTREG_DELETE_USERACCOUNT: 'POSTREG_DELETE_USERACCOUNT',
    POSTREG_ASSESS_USERACCOUNT: 'POSTREG_ASSESS_USERACCOUNT',
  
      //Retail Supplier Privilege
    VIEW_RETAIL_COUNTERPARTIES_LIST: 'RS_VIEW_RETAIL_SUPPLIER_CONFIRMATION_LIST',
    VIEW_RETAIL_COUNTERPARTIES: 'RS_VIEW_RETAIL_SUPPLIER_CONFIRMATION',
    RS_ASSESS_REQUEST: 'RS_ASSESS_RETAIL_SUPPLIER_REQUEST',
    RS_CANCEL_REQUEST: 'RS_CANCEL_RETAIL_SUPPLIER_REQUEST',
    RS_CONFIRM_POST_REG: 'RS_CONFIRM_RETAIL_SUPPLIER_CONFIRMATION_POST_REG',
    RS_CONFIRM_PRE_REG: 'RS_CONFIRM_RETAIL_SUPPLIER_CONFIRMATION_PRE_REG',
    RS_CREATE_MO: 'RS_CREATE_RETAIL_SUPPLIER_CONFIRMATION_MO',
    RS_CREATE_POST_REG: 'RS_CREATE_RETAIL_SUPPLIER_CONFIRMATION_POST_REG',
    Rs_CREATE_PRE_REG: 'RS_CREATE_RETAIL_SUPPLIER_CONFIRMATION_PRE_REG',
    RS_ROUTE_REQUEST: 'RS_ROUTE_RETAIL_SUPPLIER_REQUEST',
    RS_UPDATE_ACTIVE_TP: 'RS_UPDATE_ACTIVE_RETAIL_SUPPLIER_TP',
    RS_UPDATE_NON_ACTIVE_TP: 'RS_UPDATE_NON_ACTIVE_RETAIL_SUPPLIER_TP',
    RS_UPDATE_CONFIRMATION_MO: 'RS_UPDATE_RETAIL_SUPPLIER_CONFIRMATION_MO',
  
  
  
    VIEW_COUNTERPARTY_LIST: 'CM_VIEW_COUNTERPARTY_CONFIRMATION_LIST',
    VIEW_CUSTOMER_ENROLLMENT_LIST: 'CM_VIEW_CUSTOMER_ENROLLMENT_LIST',
    VIEW_CUSTOMER_SWITCHING_LIST: 'CM_VIEW_CUSTOMER_SWITCHING_LIST',
    VIEW_COUNTERPARTY: 'CM_VIEW_COUNTERPARTY_CONFIRMATION',
    VIEW_CUSTOMER_ENROLLMENT: 'CM_VIEW_CUSTOMER_ENROLLMENT',
    VIEW_CUSTOMER_SWITCHING: 'CM_VIEW_CUSTOMER_SWITCHING',
    VIEW_EXPIRED_DOCS: 'REG_VIEW_EXPIRED_DOCUMENTS',
    VIEW_EXPIRING_DOCS: 'REG_VIEW_EXPIRING_DOCUMENTS',
    VIEW_EXPIRING_EXPIRED_DOCS: 'REG_VIEW_EXPIRING_EXPIRED_DOCUMENTS',
    VIEW_SOLR_EVENT: 'CM_VIEW_SOLR_EVENT',
    MANAGE_SOLR_EVENT: 'CM_SOLR_EVENT',
    CANCEL_COUNTERPARTY: 'CM_CANCEL_COUNTERPARTY_CONFIRMATION',
    CREATE_CUST_SWITCH: 'CM_CREATE_CUSTOMER_SWITCH',
    ASSESS_CUST_SWITCH: 'CM_ASSESS_CUSTOMER_SWITCH_REQUEST',
    ROUTE_CUST_SWITCH: 'CM_ROUTE_CUSTOMER_SWITCH_REQUEST',
    CANCEL_CUSTOMER_ENROLLMENT: 'CM_CANCEL_CUSTOMER_ENROLLMENT',
    CREATE_CUSTOMER_ENROLLMENT: 'CM_CREATE_CUSTOMER_ENROLLMENT',
    CREATE_CUSTOMER_ENROLLMENT_MO: 'CM_CREATE_CUSTOMER_ENROLLMENT_MO',
    UPDATE_CUSTOMER_ENROLLMENT_MO: 'CM_UPDATE_CUSTOMER_ENROLLMENT_MO',
    UPDATE_CUSTOMER_ENROLLMENT: 'CM_UPDATE_CUSTOMER_ENROLLMENT',
    EXTEND_CUST_SWITCH_END_DATE: 'CM_EXTEND_ACTIVE_CUSTOMER_SWITCH_END_DATE',
    CM_CREATE_COUNTERPARTY_CONFIRMATION_MO: 'CM_CREATE_COUNTERPARTY_CONFIRMATION_MO',
    CM_UPDATE_COUNTERPARTY_CONFIRMATION_MO: 'CM_UPDATE_COUNTERPARTY_CONFIRMATION_MO',
    CM_UPDATE_ACTIVE_COUNTERPARTY_TP: 'CM_UPDATE_ACTIVE_COUNTERPARTY_TP',
    CM_UPDATE_NON_ACTIVE_COUNTERPARTY_TP: 'CM_UPDATE_NON_ACTIVE_COUNTERPARTY_TP',
    CM_UPDATE_CUSTOMER_SWITCH_MO: 'CM_UPDATE_CUSTOMER_SWITCH_MO',
    CM_ROUTE_COUNTERPARTY_REQUEST: 'CM_ROUTE_COUNTERPARTY_REQUEST',
    CM_ASSESS_COUNTERPARTY_REQUEST: 'CM_ASSESS_COUNTERPARTY_REQUEST',
    CM_UPDATE_INDIRECT_TP_INITIAL_PR: 'CM_UPDATE_INDIRECT_TP_INITIAL_PR',
  
    EXPORT_COUNTERPARTY_REPORT: 'EXPORT_COUNTERPARTY_CONFIRMATION_REPORT',
    EXPORT_CUSTOMER_ENROLLMENT_REPORT: 'EXPORT_CUSTOMER_ENROLLMENT_REPORT',
    EXPORT_CUSTOMER_SWITCH_REPORT: 'EXPORT_CUSTOMER_SWITCH_REPORT',
    EXPORT_WESM_REG_UPDATE_REPORT: 'EXPORT_WESM_REG_UPDATE_REPORT',
  
    VIEW_INDIRECT_CC_LIST: 'REG_VIEW_INDIRECT_CC_REGISTRATION',
    VIEW_INDIRECT_MEMBER_LIST: 'REG_VIEW_INDIRECT_REGISTRATION_LIST',
    CREATE_INDIRECT_CC: 'REG_CREATE_INDIRECT_CC_REGISTRATION',
  
    MANAGE_MSP: 'REG_CREATE_MSP_REGISTRATION',
  
    VIEW_WESM_REGISTRATION_UPDATE_REPORT : 'VIEW_WESM_REGISTRATION_UPDATE_REPORT',
    VIEW_PRUDENTIAL_REQ_SECURITY_DEPOSIT_LIST : 'VIEW_PRUDENTIAL_REQ_SECURITY_DEPOSIT_LIST',
    VIEW_PRUDENTIAL_REQ_EXPIRING_SECURITY_DEPOSIT_LIST : 'VIEW_PRUDENTIAL_REQ_EXPIRING_SECURITY_DEPOSIT_LIST',
    VIEW_PRUDENTIAL_REQ_EXEMPTION_LIST: 'VIEW_PRUDENTIAL_REQ_EXEMPTION_LIST',
    UPDATE_PRUDENTIAL_REQ_EXEMPTION: 'UPDATE_PRUDENTIAL_REQ_EXEMPTION',
    UPLOAD_PRUDENTIAL_INITIAL_CSV: 'UPLOAD_PRUDENTIAL_INITIAL_CSV',
    VIEW_PR_SEC_DEP_EMAIL_LIST: 'VIEW_PR_SEC_DEP_EMAIL_LIST',
    CREATE_PR_SEC_DEP_EMAIL: 'CREATE_PR_SEC_DEP_EMAIL',
    UPDATE_PR_SEC_DEP_EMAIL: 'UPDATE_PR_SEC_DEP_EMAIL',
    DELETE_PR_SEC_DEP_EMAIL: 'DELETE_PR_SEC_DEP_EMAIL',
    ADM_VIEW_HOLIDAY_LIST : 'ADM_VIEW_HOLIDAY_LIST',
    CREATE_HOLIDAY: 'ADM_CREATE_HOLIDAY',
    UPDATE_HOLIDAY: 'ADM_UPDATE_HOLIDAY',
    DELETE_HOLIDAY: 'ADM_DELETE_HOLIDAY',
    VIEW_HOLIDAY: 'ADM_VIEW_HOLIDAY',
    PR_SD_CREATE : 'PR_SD_CREATE',
    PR_SD_UPDATE : 'PR_SD_UPDATE',
    PR_SD_POST_WITHDRAWAL_OR_DRAWDOWN : 'PR_SD_POST_WITHDRAWAL_OR_DRAWDOWN',
    PR_SD_VIEW : 'PR_SD_VIEW',
    PR_SD_ASSESS : 'PR_SD_ASSESS',
    PR_SD_EXPORT_CSV : 'PR_SD_EXPORT_CSV',
    PR_SD_EXPIRING_VIEW : 'PR_SD_EXPIRING_VIEW',
    PR_SD_EXPIRING_EXPORT_CSV : 'PR_SD_EXPIRING_EXPORT_CSV',
    PR_SD_EXPIRING_APPROVE_FIRST_NOTIFICATION : 'PR_SD_EXPIRING_APPROVE_FIRST_NOTIFICATION',
    PR_SD_EXPIRING_APPROVE_SECOND_NOTIFICATION : 'PR_SD_EXPIRING_APPROVE_SECOND_NOTIFICATION',
    VIEW_PR_SD_EXPIRING_SENT_NOTIFICATION_LIST : 'VIEW_PR_SD_EXPIRING_SENT_NOTIFICATION_LIST',
    PR_SD_EXPIRING_SENT_NOTIFICATION_EXPORT_CSV : 'PR_SD_EXPIRING_SENT_NOTIFICATION_EXPORT_CSV',
    PR_EX_EXPORT_CSV : 'PR_EX_EXPORT_CSV',
    ADM_EXPORT_CSV_HOLIDAY: 'ADM_EXPORT_CSV_HOLIDAY',
    PR_SDE_EXPORT_CSV: 'PR_SDE_EXPORT_CSV',
    ADM_MANAGE_DATA_EXTRACTION: 'ADM_MANAGE_DATA_EXTRACTION',
    VIEW_BCQ_DOWNLOAD_TEMPLATE: 'VIEW_BCQ_DOWNLOAD_TEMPLATE',
    ADM_SD_EXPIRY_NOTIFICATION: 'ADM_SD_EXPIRY_NOTIFICATION',
    PR_BREAKDOWN_EXPORT_CSV: 'PR_BREAKDOWN_EXPORT_CSV',
    VIEW_PR_OUT_BAL_LIST: 'VIEW_PR_OUT_BAL_LIST',
    CREATE_PR_OUT_BAL: 'CREATE_PR_OUT_BAL',
    UPDATE_PR_OUT_BAL: 'UPDATE_PR_OUT_BAL',
    DELETE_PR_OUT_BAL: 'DELETE_PR_OUT_BAL',
    PR_OUT_BAL_EXPORT_CSV : 'PR_OUT_BAL_EXPORT_CSV',
    ADM_CFG_ANY_REGISTERED_CUST_ENROLL: 'ADM_CFG_ANY_REGISTERED_CUST_ENROLL',
    ADM_GEN_TO_GEN_BCQ_UPLOAD: 'ADM_GEN_TO_GEN_BCQ_UPLOAD',
    ADM_LOAD_TO_LOAD_BCQ_UPLOAD: 'ADM_LOAD_TO_LOAD_BCQ_UPLOAD',
    ADM_LOAD_TO_GEN_BCQ_UPLOAD: 'ADM_LOAD_TO_GEN_BCQ_UPLOAD',
    ADM_BP_ANNUAL_AGGREGATION: 'ADM_BP_ANNUAL_AGGREGATION',
    ADM_BP_HISTORICAL_WESM_BILL: 'ADM_BP_HISTORICAL_WESM_BILL',
    ADM_CFG_CALCULATE_SINGLE_BUYER: 'ADM_CFG_CALCULATE_SINGLE_BUYER',
  
    ADM_PASSWORD_EXPIRY_NOTIFICATION: 'ADM_PASSWORD_EXPIRY_NOTIFICATION',
    ADM_SUPER_USER: 'ADM_SUPER_USER',
    //security deposit dashboard
    VIEW_DASHBOARD_FIRST_EXPIRING_SEC_DEPOSIT: 'VIEW_DASHBOARD_FIRST_EXPIRING_SEC_DEPOSIT',
    VIEW_DASHBOARD_SECOND_EXPIRING_SEC_DEPOSIT: 'VIEW_DASHBOARD_SECOND_EXPIRING_SEC_DEPOSIT',
    VIEW_DASHBOARD_FIRST_EXPIRING_SEC_DEPOSIT_SEND: 'VIEW_DASHBOARD_FIRST_EXPIRING_SEC_DEPOSIT_SENT',
    VIEW_DASHBOARD_SECOND_EXPIRING_SEC_DEPOSIT_SEND: 'VIEW_DASHBOARD_SECOND_EXPIRING_SEC_DEPOSIT_SENT',
  
    // maximum exposure
  
    VIEW_MAXIMUM_EXPOSURE_LIST : 'VIEW_MAXIMUM_EXPOSURE_LIST',
    MAXIMUM_EXPOSURE_EXPORT_CSV : 'MAXIMUM_EXPOSURE_EXPORT_CSV',
    CREATE_MAXIMUM_EXPOSURE : 'CREATE_MAXIMUM_EXPOSURE',
    UPDATE_MAXIMUM_EXPOSURE : 'UPDATE_MAXIMUM_EXPOSURE',
    IMPORT_MAXIMUM_EXPOSURE : 'IMPORT_MAXIMUM_EXPOSURE',
  
    // Margin Call Summary
    MARGIN_CALL_SUMMARY_VIEW: 'MARGIN_CALL_SUMMARY_VIEW',
    MARGIN_CALL_SUMMARY_CONFIRMATION_VIEW: 'MARGIN_CALL_SUMMARY_CONFIRMATION_VIEW',
    MARGIN_CALL_SUMMARY_CONFIRM: 'MARGIN_CALL_SUMMARY_CONFIRM',
    MARGIN_CALL_SUMMARY_GENERATE: 'MARGIN_CALL_SUMMARY_GENERATE',
    MARGIN_CALL_SUMMARY_GENERATE_DOCUMENT: 'MARGIN_CALL_SUMMARY_GENERATE_DOCUMENT',
    MARGIN_CALL_SUMMARY_UPLOAD_DOCUMENT: 'MARGIN_CALL_SUMMARY_UPLOAD_DOCUMENT',
    MARGIN_CALL_SUMMARY_ISSUE_NOTICE: 'MARGIN_CALL_SUMMARY_ISSUE_NOTICE',
    MARGIN_CALL_SUMMARY_EXPORT_CSV: 'MARGIN_CALL_SUMMARY_EXPORT_CSV',
    MARGIN_CALL_SUMMARY_ADD_REMARKS: 'MARGIN_CALL_SUMMARY_ADD_REMARKS',
  
    MARGIN_CALL_NOTICE_ISSUANCE_VIEW: 'MARGIN_CALL_NOTICE_ISSUANCE_VIEW',
    MARGIN_CALL_NOTICE_ISSUANCE_UPLOAD: 'MARGIN_CALL_NOTICE_ISSUANCE_UPLOAD',
    MARGIN_CALL_NOTICE_ISSUANCE_ISSUE : 'MARGIN_CALL_NOTICE_ISSUANCE_ISSUE',
    MARGIN_CALL_NOTICE_ISSUANCE_CSV: 'MARGIN_CALL_NOTICE_ISSUANCE_CSV',
  
    MARGIN_CALL_NOTICE_HISTORY_VIEW: 'MARGIN_CALL_NOTICE_HISTORY_VIEW',
    MARGIN_CALL_NOTICE_HISTORY_DOWNLOAD: 'MARGIN_CALL_NOTICE_HISTORY_DOWNLOAD',
    MARGIN_CALL_NOTICE_HISTORY_EXPORT_CSV: 'MARGIN_CALL_NOTICE_HISTORY_EXPORT_CSV',
  
    IMPORT_IPR_DATA: 'IMPORT_IPR_DATA',
    UPDATE_IPR_DATA: 'UPDATE_IPR_DATA',
    CONFIRM_IPR_DATA: 'CONFIRM_IPR_DATA',
    EXPORT_IRP_DATA: 'EXPORT_IRP_DATA',
  
    // PR Monitoring Report
    VIEW_PR_MONITOR_REPORT: 'VIEW_PR_MONITOR_REPORT',
    EXPORT_PR_MONITOR_REPORT: 'EXPORT_PR_MONITOR_REPORT',
  
    // Historical WESM Bill
    VIEW_HISTORICAL_WESM_BILL: 'VIEW_HISTORICAL_WESM_BILL',
    EXPORT_HISTORICAL_WESM_BILL_CSV: 'EXPORT_HISTORICAL_WESM_BILL_CSV',
  
    //enable supply contract hex
    VIEW_SUPPLY_CONTRACT_LIST: 'VIEW_SUPPLY_CONTRACT_LIST',
    VIEW_BILLING_CONFIGURATION_LIST: 'VIEW_BILLING_CONFIGURATION_LIST',
    EXPORT_BILLING_CONFIGURATION_LIST: 'EXPORT_BILLING_CONFIGURATION_LIST',
  
    // MIRF Upload
    MIRF_UPLOAD_VIEW: 'MIRF_UPLOAD_VIEW',
    MIRF_UPLOAD_IMPORT: 'MIRF_UPLOAD_IMPORT',
    MIRF_UPLOAD_UPDATE: 'MIRF_UPLOAD_UPDATE',
    MIRF_UPLOAD_SUBMIT: 'MIRF_UPLOAD_SUBMIT',
  
    // MIRF Summary
    MIRF_SUMMARY_EXPORT_CSV: 'MIRF_SUMMARY_EXPORT_CSV',
    MIRF_SUMMARY_VIEW: 'MIRF_SUMMARY_VIEW',
    MIRF_DATA_EXPORT_PDF: 'MIRF_DATA_EXPORT_PDF',
  
      //Modify Signatory Config
    ADM_MCN_SIGNATORY: 'ADM_MCN_SIGNATORY',
    ADM_MCN_SIGNATORY_TITLE : 'ADM_MCN_SIGNATORY_TITLE',
    ADM_MCN_ANNOTATION : 'ADM_MCN_ANNOTATION',
    ADM_EXP_PRSD_NOTICE_TITLE : 'ADM_EXP_PRSD_NOTICE_TITLE',
    ADM_EXP_PRSD_NOTICE_SIGNATORY : 'ADM_EXP_PRSD_NOTICE_SIGNATORY',
  
    // MODIFY DAILY / MONTHLY Available Data Days
    ADM_DAILY_AVAILABLE_DATA_DOWNLOAD: 'ADM_DAILY_AVAILABLE_DATA_DOWNLOAD',
    ADM_MONTHLY_AVAILABLE_DATA_DOWNLOAD: 'ADM_MONTHLY_AVAILABLE_DATA_DOWNLOAD',
  
    UPLOAD_AMS_BILLING_INFO : 'UPLOAD_AMS_BILLING_INFO',
    GENERATE_DRAWDOWN_SUMMARY : 'GENERATE_DRAWDOWN_SUMMARY',
    CONFIRM_DRAWDOWN_SUMMARY : 'CONFIRM_DRAWDOWN_SUMMARY',
    VIEW_GENERATE_DRAWDOWN_SUMMARY : 'VIEW_GENERATE_DRAWDOWN_SUMMARY',
    VIEW_CONFIRM_DRAWDOWN_SUMMARY : 'VIEW_CONFIRM_DRAWDOWN_SUMMARY',
    VIEW_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY: 'VIEW_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY',
    DOWNLOAD_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY: 'DOWNLOAD_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY',
    VIEW_HISTORICAL_DRAWDOWN_SUMMARY: 'VIEW_HISTORICAL_DRAWDOWN_SUMMARY',
    DRAWDOWN_SUMMARY_EXPORT_CSV : 'DRAWDOWN_SUMMARY_EXPORT_CSV',
    DRAWDOWN_CONFIRMED_EXPORT_CSV : 'DRAWDOWN_CONFIRMED_EXPORT_CSV',
    DRAWDOWN_HISTORICAL_EXPORT_CSV : 'DRAWDOWN_HISTORICAL_EXPORT_CSV',
    DRAWDOWN_FOR_ISSUANCE_EXPORT_CSV : 'DRAWDOWN_FOR_ISSUANCE_EXPORT_CSV',
    DOWNLOAD_HISTORICAL_DRAWDOWN_SUMMARY: 'DOWNLOAD_HISTORICAL_DRAWDOWN_SUMMARY',
    ISSUE_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY : 'ISSUE_NOTICE_ISSUANCE_DRAWDOWN_SUMMARY',
    PREPARE_DOCUMENTS_DRAWDOWN_SUMMARY : 'PREPARE_DOCUMENTS_DRAWDOWN_SUMMARY',
    UPLOAD_DOCUMENT_DRAWDOWN_NOTICE_ISSUANCE : 'UPLOAD_DOCUMENT_DRAWDOWN_NOTICE_ISSUANCE',
  
    VIEW_CREATED_PARTICIPANTS : 'VIEW_CREATED_PARTICIPANTS',
    CREATE_INTERNAL_PARTICIPANT : 'CREATE_INTERNAL_PARTICIPANT',
    CREATE_INTERNAL_INDIRECT_CC : 'CREATE_INTERNAL_INDIRECT_CC',
    VIEW_SUSPENDED_PARTICIPANTS : 'VIEW_SUSPENDED_PARTICIPANTS',
    VIEW_FACILITY_LIST : 'VIEW_FACILITY_LIST',
    CREATE_INTERNAL_FACILITY : 'CREATE_INTERNAL_FACILITY',
    UPDATE_INTERNAL_FACILITY : 'UPDATE_INTERNAL_FACILITY',
    VIEW_FACILITIES_FOR_ACTIVATION : 'VIEW_FACILITIES_FOR_ACTIVATION',
    VIEW_FACILITIES_FOR_TRANSFER : 'VIEW_FACILITIES_FOR_TRANSFER',
    ACTIVATE_FACILITY: 'ACTIVATE_FACILITY',
    LIFT_SUSPENSION_OF_PARTICIPANT: 'LIFT_SUSPENSION_OF_PARTICIPANT',
    FACILITY_ADD_MTN : 'FACILITY_ADD_MTN',
    FACILITY_ADD_SCHED_POINT : 'FACILITY_ADD_SCHED_POINT',
    POSTREG_UPDATE_FACILITY_MO: 'POSTREG_UPDATE_FACILITY_MO',
  
    CAN_DECOMMISSION: 'MIR_DECOMMISSION_MIRF',
    REG_OVERRIDE_REGINF: 'REG_OVERRIDE_REGINF',
    MANAGE_FIELD_SETTINGS: 'MANAGE_FIELD_SETTINGS',
    MANAGE_SEC: 'MANAGE_SEC',
  
    //  MANAGE VIRTUAL METERING POINT
    VMP_MAINTENANCE_CREATE: "VMP_MAINTENANCE_CREATE",
    VMP_MAINTENANCE_UPDATE: "VMP_MAINTENANCE_UPDATE",
    VMP_MAINTENANCE_VIEW: "VMP_MAINTENANCE_VIEW",
  
    ADM_UPLOAD_LOGO: 'ADM_UPLOAD_LOGO',
    VIEW_FINANCIAL_INFO_PAGE: 'VIEW_FINANCIAL_INFO_PAGE',
    FACILITY_MO_FIELDS: 'FACILITY_MO_FIELDS',
    PRE_REG_ADD_FACILITY : 'PRE_REG_ADD_FACILITY',
    POST_REG_ADD_FACILITY : 'POST_REG_ADD_FACILITY',
  
    VIEW_CALENDAR : 'VIEW_CALENDAR',
    VIEW_DOWNLOAD_METER_STL_DATA: 'VIEW_DOWNLOAD_METER_STL_DATA',
  
    REQUEST_TRANSFER_FACILITY: 'REQUEST_TRANSFER_FACILITY',
    CANCEL_TRANSFER_FACILITY: 'CANCEL_TRANSFER_FACILITY',
    APPROVE_TRANSFER_FACILITY_REQUEST: 'APPROVE_TRANSFER_FACILITY_REQUEST',
    DENY_TRANSFER_FACILITY_REQUEST: 'DENY_TRANSFER_FACILITY_REQUEST',
    CALCULATE_IPR: 'CALCULATE_IPR'
  
  }

  export const PHASE_TWO_AUTHORITIES = {
    // Settlement Related Permissions
    VALIDATE_INPUT: 'VALIDATE_INPUT', // Validate Inputs
    RUN_ADJUSTMENTS: 'RUN_ADJUSTMENTS', // Run Adjustments
    RUN_ADDTL_COMP: 'RUN_ADDTL_COMP', // Run Additional Compensation
    VIEW_ADDTL_COMP: 'VIEW_ADDTL_COMP', // View Additional Compensation Page
    VIEW_STL_PROCESS: 'VIEW_STL_PROCESS', // View Settlement Process Page
    AC_CALC_GMR_VAT: 'AC_CALC_GMR_VAT', // Calculate GMR/VAT AC (used by AC)
    FINALIZE_CALC: 'FINALIZE_CALC', // Finalize Calculations (used by AC)
    AC_VIEW_AMS_INV_FOR_UPDATE: 'AC_VIEW_AMS_INV_FOR_UPDATE',
    AC_UPDATE_AMS_INV_FOR_UPDATE: 'AC_UPDATE_AMS_INV_FOR_UPDATE',
    GENERATE_FILES: 'GENERATE_FILES', // Generate Files (used by AC)
    SET_BILLING_ID_CONFIG: 'SET_BILLING_ID_CONFIG', // Set Billing ID Masterlist Configuration
    SET_BILLING_ID_SEIN_MAPPING: 'SET_BILLING_ID_SEIN_MAPPING', // Set Billing ID SEIN Mapping
    SET_BILLING_ID_MTN_MAPPING: 'SET_BILLING_ID_MTN_MAPPING', // Set Billing ID MTN Mapping
    SET_BILLING_PERIOD_CONFIG: 'SET_BILLING_PERIOD_CONFIG', // Set Billing Period Configuration
    SET_CHARGE_ID_CONFIG: 'SET_CHARGE_ID_CONFIG', // Set Charge ID Configuration
    SET_MARKET_FEE_MODE: 'SET_MARKET_FEE_MODE', // Set Market Fee Mode
    SET_RESERVE_PROCESS_CONFIG: 'SET_RESERVE_PROCESS_CONFIG', // Set Reserve Process Configuration
    SET_COST_RECOVERY_MODE: 'SET_COST_RECOVERY_MODE', // Set Reserve Cost Recovery Mode
    SET_MRU_CONFIG: 'SET_MRU_CONFIG', // Set Must Run Unit parameter
    SET_STL_FILE_LOCATION: 'SET_STL_FILE_LOCATION', // Set Settlement File Location
    SET_STL_GEN_CONFIG: 'SET_STL_GEN_CONFIG', // Set Settlement General Configuration
    APPROVE_STL_TP_WORKLIST: 'APPROVE_STL_TP_WORKLIST', // Approve Settlement Trading Participant Worklist
    APPROVE_STL_MP_WORKLIST: 'APPROVE_STL_MP_WORKLIST', // Approve Settlement Metering Point Worklist
    SET_TP_PASSWORD_CONFIG: 'SET_TP_PASSWORD_CONFIG', // Set TP Billing ID Password

    // Metering Related Permissions
    VIEW_IMPORT_METERING_CONFIGURATION: 'VIEW_IMPORT_METERING_CONFIGURATION', // View Import Metering Configuration
    IMPORT_RCOA_CHANNEL_CONFIGURATION: 'IMPORT_RCOA_CHANNEL_CONFIGURATION', // Import RCOA Metering Point Channel Configuration
    IMPORT_MTN_CONFIGURATION: 'IMPORT_MTN_CONFIGURATION', // Import MTN Configuration Model from xls
    IMPORT_MTN_MODEL_GROUP_LIST: 'IMPORT_MTN_MODEL_GROUP_LIST', // Import MTN Model Group List
    IMPORT_MTN_MODEL_GROUP_SCHEDULE: 'IMPORT_MTN_MODEL_GROUP_SCHEDULE', // Import MTN Model Group Schedule
    VIEW_METER_PROCESS: 'VIEW_METER_PROCESS', // View Meter Process
    RUN_WESM_METER_DATA: 'RUN_WESM_METER_DATA', // Run WESM Meter Data
    RUN_RCOA_METER_DATA: 'RUN_RCOA_METER_DATA', // Run RCOA Meter Data
    RUN_SETTLEMENT_READY_METER_DATA: 'RUN_SETTLEMENT_READY_METER_DATA', // Process Settlement-Ready
    FINALIZE_SETTLEMENT_READY_METER_DATA: 'FINALIZE_SETTLEMENT_READY_METER_DATA', // Process Settlement-Ready
    GENERATE_MQ_REPORT: 'GENERATE_MQ_REPORT', // Generate MQ Report
    DOWNLOAD_MQ_REPORT: 'DOWNLOAD_MQ_REPORT', // Download MQ Report
    VIEW_MTR: 'VIEW_MTR', // View MTR
    GENERATE_MTR: 'GENERATE_MTR', // Generate MTR
    DOWNLOAD_MTR: 'DOWNLOAD_MTR', // Download MTR
    UPDATE_METER_REMARKS: 'UPDATE_METER_REMARKS', // Update MTR Remarks
    UPDATE_MSP_REMARKS: 'UPDATE_MSP_REMARKS', // Update MSP Remarks
    CLOSE_SELECTED_MTR_REMARKS: 'CLOSE_SELECTED_MTR_REMARKS', // Close Selected Remarks
    VIEW_IMPORT_SETTLEMENT_METERING_CONFIGURATION: 'VIEW_IMPORT_SETTLEMENT_METERING_CONFIGURATION', // View Settlement Metering Point Configuration
    IMPORT_SETTLEMENT_METERING_CONFIGURATION: 'IMPORT_SETTLEMENT_METERING_CONFIGURATION', // Import Settlement Metering Point Configuration
    IMPORT_VIRTUAL_METERING_POINT_MAPPING: 'IMPORT_VIRTUAL_METERING_POINT_MAPPING', // Import Virtual Metering Point Mapping
    VIEW_SHIFTING_ANALYSIS: 'VIEW_SHIFTING_ANALYSIS', // View RTU Comparison
    GENERATE_COMPARISON_GRAPH: 'GENERATE_COMPARISON_GRAPH', // Generate Comparison Graph
    PROCESS_MTN_SHIFTING_SCHEDULE: 'PROCESS_MTN_SHIFTING_SCHEDULE', // Generate Shifting Comparison Graph
    SET_STL_SEIN_CONFIG: 'SET_STL_SEIN_CONFIG', // Set Settlement SEIN Masterlist Configuration
    SET_VSEIN_MAPPING: 'SET_VSEIN_MAPPING', // Set Virtual SEIN Mapping for Meter Process
    SET_MTN_MODEL_CONFIG: 'SET_MTN_MODEL_CONFIG', // Set MTN Model Configuration
    SET_MTN_LOOP_CONFIG: 'SET_MTN_LOOP_CONFIG', // Set MTN Loop Configuration
    SET_MTN_GROUP_SCHED_SCHED: 'SET_MTN_GROUP_SCHED_SCHED', // Set MTN Group and Schedule Configuration
    SET_RCOA_CHANNEL_CONFIG: 'SET_RCOA_CHANNEL_CONFIG', // Set RCOA Channel Configuration
    SET_RCOA_GRIDOFFTAKE_MAPPING: 'SET_RCOA_GRIDOFFTAKE_MAPPING', // Set RCOA Gridofftake Metering Points Mapping
    SET_MET_GEN_CONFIG: 'SET_MET_GEN_CONFIG', // Set Metering General Configuration
    APPROVE_MET_MP_WORKLIST: 'APPROVE_MET_MP_WORKLIST', // Approve Meter Process Metering Point Worklist
    VIEW_MET_CFG: 'VIEW_MET_CFG', // View Metering Maintenance Configuration
    SET_MET_CFG: 'SET_MET_CFG', // Set Metering Maintenance Configuration

    // Trading / TOD related permissions
    RUN_EPS_MANUAL: 'RUN_EPS_MANUAL',
    RUN_RPS_MANUAL: 'RUN_RPS_MANUAL',
    RUN_RBCQ_MANUAL: 'RUN_RBCQ_MANUAL',
    RUN_RTU_MANUAL: 'RUN_RTU_MANUAL',
    RUN_MTN_MANUAL: 'RUN_MTN_MANUAL',
    RUN_MRU_MANUAL: 'RUN_MRU_MANUAL',
    RUN_ASIE_MANUAL: 'RUN_ASIE_MANUAL',
    RUN_COG_MANUAL: 'RUN_COG_MANUAL',
    RUN_SGAD_MANUAL: 'RUN_SGAD_MANUAL',
    VIEW_IMPORT_SUMMARY: 'VIEW_IMPORT_SUMMARY',
    SET_TOD_GEN_CONFIG: 'SET_TOD_GEN_CONFIG',

    // Admin related permissions
    SET_UPDATE_EPS_SCHEDULE: 'SET_UPDATE_EPS_SCHEDULE',
    SET_UPDATE_RPS_SCHEDULE: 'SET_UPDATE_RPS_SCHEDULE',
    SET_UPDATE_RBCQ_SCHEDULE: 'SET_UPDATE_RBCQ_SCHEDULE',
    SET_UPDATE_RTU_SCHEDULE: 'SET_UPDATE_RTU_SCHEDULE',
    VIEW_IMPORT_SCHEDULE: 'VIEW_IMPORT_SCHEDULE',

    TA_GENERATE_ENERGY_FILE: 'TA_GENERATE_ENERGY_FILE',
    TA_GENERATE_RESERVE_FILE: 'TA_GENERATE_RESERVE_FILE',
    TA_CALCULATE_GMRVAT: 'TA_CALCULATE_GMRVAT',
    TA_GENERATE_IW: 'TA_GENERATE_IW',
    TA_CALCULATE_TA: 'TA_CALCULATE_TA',
    TA_FINALIZE: 'TA_FINALIZE',
    EMF_GENERATE_IW: 'EMF_GENERATE_IW',
    EMF_CALCULATE: 'EMF_CALCULATE',
    EMF_FINALIZE: 'EMF_FINALIZE',
    EMF_GENERATE_EMF_FILE: 'EMF_GENERATE_EMF_FILE',
    RMF_GENERATE_IW: 'RMF_GENERATE_IW',
    RMF_CALCULATE: 'RMF_CALCULATE',
    RMF_FINALIZE: 'RMF_FINALIZE',
    RMF_GENERATE_RMF_FILE: 'RMF_GENERATE_RMF_FILE',

    // Activity log
    VIEW_ACTIVITY_LOG: 'VIEW_ACTIVITY_LOG',

    // Upload billing statement
    UPLOAD_BILLING_STATEMENT: 'UPLOAD_BILLING_STATEMENT',

    // Process transaction allocation
    PROCESS_TRANSACTION_ALLOCATION: 'PROCESS_TRANSACTION_ALLOCATION',
};