// Form Labels, Actions

export const LABELS = {
  // Actions
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  SUCCESS: 'Success',
  CONFIRMATION: 'Confirmation',
  PUBLISH: 'Publish',
  YES: 'Yes',
  NO: 'No',
  SELECT: 'Select',
  SWITCH: 'Switch',
  OK: 'Ok',
  CONTINUE: 'Continue',
  ERROR: 'Error',
  SELECT_ACTION: 'Select Action',
  PROCEED: 'Proceed',
  CHOOSE_HERE: 'Choose here',
  UPLOAD: 'Upload',
  CHOOSE_FILE: 'Choose File',
  CLEAR: 'Clear',
  UPLOAD_ERROR: 'Upload Error',
  CANCEL_RUN: 'Cancel Run',
  SET_FILTERS: 'Set Filters',
  CLEAR_FILTERS: 'Clear Filters',
  APPLY_FILTERS: 'Apply Filters',
  RUN: 'Run',
  RUN_JOB: 'Run Job',

  // Field Labels
  CONSOLIDATE: 'Consolidate',
  BASE: 'Base',
  RERUNS: 'Reruns',
  WORKSPACE_ID: 'Workspace ID',
  RUN_DATE_AND_TIME: 'Run Date and Time',
  PROCESS_TYPE: 'Process Type',
  TRADING_DATE: 'Trading Date',
  DATE_TIME_RANGE: 'Date Time Range',
  REGION_GROUP: 'Region Group',
  BILLING_PERIOD: 'Billing Period',
  MTN: 'MTN',
  STATUS: 'Status',
  ALL: 'All',
  TRANSACTION_REPORT: 'Transaction Report',
  DUE_DATE: 'Due Date',
  CALCULATE_ENERGY_TRADING_AMOUNT: 'Calculate Energy Trading Amount',
  GENERATE_MONTHLY_SUMMARY: 'Generate Monthly Summary',
  GENERATE_INPUT_WORKSPACE: 'Generate Input Workspace',

  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  SIGN_OUT: 'Sign Out',
  SWITCH_TO_SUPER_USER: 'Switch to Super User',
  SWITCH_TO_NORMAL_USER: 'Switch to Normal User',
  USER: 'User',

  NAME: 'Name',
  RUN_ID: 'Run ID',
  RUN_START: 'Run Start',
  RUN_END: 'Run End',
  DURATION: 'Duration',
  RUN_BY: 'Run By',

  MQ_UPLOADER: 'MQ Uploader',
  ONGOING: 'Ongoing',
  HISTORY: 'History',

  TRANSACTION_ID: 'Transaction ID',
  MSP: 'MSP',
  FILE_NAME: 'File Name',
  CATEGORY: 'Category',
  BILLING_DATE: 'Billing Date',
  SIZE: 'Size',
  CONVERSION_TYPE: 'Conversion Type',
  UPLOAD_DATA_AS_IS: 'Upload Data as is',
  CONVERT_TO_5_MIN: 'Convert to 5 mins',
  TRADING_DAY: 'Trading Day',
  INTERVAL: 'Interval',
  TRADING_MONTH: 'Trading Month',
  SELECTED_FILES: 'Selected Files',
  START_IMPORT: 'Start Import',

  UPLOADING_DATE_AND_TIME: 'Uploading Date and Time',
  TOTAL_NUMBER_OF_FILES_UPLOADED: 'Total Number of Files Uploaded',
  NO_OF_FILES_SUCCESSFULLY_UPLOADED: 'No. of files successfully uploaded',
  NO_OF_FILES_REJECTED: 'No. of files rejected',

  DAILY: 'Daily',
  MONTHLY: 'Monthly',
  CORRECTED_METER_DATA_DAILY: 'Corrected Meter Data (Daily)',
  CORRECTED_METER_DATA_MONTHLY: 'Corrected Meter Data (Monthly)',
  QUEUED_FOR_PROCESSING: 'Queued for Processing',

  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  START_END_DATE: 'Start and End Date',

}