// Form Labels, Actions

export const LABELS = {
  // Actions
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  SUCCESS: 'Success',
  CONFIRMATION: 'Confirmation',
  PUBLISH: 'Publish',
  YES: 'Yes',
  NO: 'No',
  SELECT: 'Select',
  SWITCH: 'Switch',
  OK: 'Ok',
  CONTINUE: 'Continue',
  ERROR: 'Error',
  SELECT_ACTION: 'Select Action',
  PROCEED: 'Proceed',
  CHOOSE_HERE: 'Choose here',
  UPLOAD: 'Upload',
  CHOOSE_FILE: 'Choose File',
  CLEAR: 'Clear',
  UPLOAD_ERROR: 'Upload Error',
  CANCEL_RUN: 'Cancel Run',
  SET_FILTERS: 'Set Filters',
  CLEAR_FILTERS: 'Clear Filters',
  APPLY_FILTERS: 'Apply Filters',
  RUN: 'Run',
  RUN_JOB: 'Run Job',
  GENERATE: 'Generate',
  DOWNLOAD: 'Download',
  ACTIONS: 'Actions',
  ACTION: 'Action',
  DELETE: 'Delete',
  SELECT_ALL: 'Select All',
  DESELECT_ALL: 'Deselect All',
  ADD: 'Add',
  SAVE: 'Save',
  SEARCH: 'Search',
  UPDATE: 'Update',

  // Field Labels
  CONSOLIDATE: 'Consolidate',
  BASE: 'Base',
  RERUNS: 'Reruns',
  WORKSPACE_ID: 'Workspace ID',
  RUN_DATE_AND_TIME: 'Run Date and Time',
  PROCESS_TYPE: 'Process Type',
  TRADING_DATE: 'Trading Date',
  DATE_TIME_RANGE: 'Date Time Range',
  REGION_GROUP: 'Region Group',
  BILLING_PERIOD: 'Billing Period',
  MTN: 'MTN',
  STATUS: 'Status',
  ALL: 'All',
  TRANSACTION_REPORT: 'Transaction Report',
  DUE_DATE: 'Due Date',
  CALCULATE_ENERGY_TRADING_AMOUNT: 'Calculate Energy Trading Amount',
  CALCULATE_RESERVE_TRADING_AMOUNT: 'Calculate Reserve Trading Amount',
  SETTLEMENT_CALCULATION: 'Settlement Calculation',
  RESERVE_SETTLEMENT_CALCULATION: 'Reserve Settlement Calculation',
  GENERATE_MONTHLY_SUMMARY: 'Generate Monthly Summary',
  GENERATE_INPUT_WORKSPACE: 'Generate Input Workspace',
  GENERATE_ENERGY_INPUT_WORKSPACE: 'Generate Energy Input Workspace',
  GENERATE_RESERVE_INPUT_WORKSPACE: 'Generate Reserve Input Workspace',
  METERING_WORKSPACE_ID: 'Metering Workspace ID',
  NULLIFIED_WORKSPACE_ID: 'Nullified Workspace ID',
  ADJUSTMENT_WORKSPACE_ID: 'Adjustment Workspace ID',

  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  SIGN_OUT: 'Sign Out',
  SWITCH_TO_SUPER_USER: 'Switch to Super User',
  SWITCH_TO_NORMAL_USER: 'Switch to Normal User',
  USER: 'User',

  NAME: 'Name',
  RUN_ID: 'Run ID',
  RUN_START: 'Run Start',
  RUN_END: 'Run End',
  DURATION: 'Duration',
  RUN_BY: 'Run By',

  MQ_UPLOADER: 'MQ Uploader',
  METERING_MASTERFILE: 'Metering Masterfile',
  METER_DATA_VALIDATION: 'Meter Data Validation',
  RECORD: 'Record',
  ONGOING: 'Ongoing',
  HISTORY: 'History',

  TRANSACTION_ID: 'Transaction ID',
  MSP: 'MSP',
  FILE_NAME: 'File Name',
  CATEGORY: 'Category',
  BILLING_DATE: 'Billing Date',
  SIZE: 'Size',
  CONVERSION_TYPE: 'Conversion Type',
  UPLOAD_DATA_AS_IS: 'Upload Data as is',
  CONVERT_TO_5_MIN: 'Convert to 5 mins',
  TRADING_DAY: 'Trading Day',
  INTERVAL: 'Interval',
  TRADING_MONTH: 'Trading Month',
  SELECTED_FILES: 'Selected Files',
  START_IMPORT: 'Start Import',

  UPLOADING_DATE_AND_TIME: 'Uploading Date and Time',
  TOTAL_NUMBER_OF_FILES_UPLOADED: 'Total Number of Files Uploaded',
  NO_OF_FILES_SUCCESSFULLY_UPLOADED: 'No. of files successfully uploaded',
  NO_OF_FILES_REJECTED: 'No. of files rejected',

  DAILY: 'Daily',
  MONTHLY: 'Monthly',
  CORRECTED_DAILY: 'Corrected Meter Data (Daily)',
  CORRECTED_MONTHLY: 'Corrected Meter Data (Monthly)',
  QUEUED_FOR_PROCESSING: 'Queued for Processing',

  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  START_END_DATE: 'Start and End Date',
  BILLING_RUN_TYPE: 'Billing Run Type',
  FILE: 'File',
  DATE_SAVED: 'Date Saved',
  SAVED_BY: 'Saved By',

  LINE_RENTAL_STATUS: 'Line Rental Status',

  CALCULATE_ENERGY_TRANSACTION_ALLOCATION: 'Calculate Energy Transaction Allocation',
  CALCULATE_GMR_VAT: 'Calculate GMR/VAT',
  CALCULATE_LINE_RENTAL: 'Calculate Line Rental',
  CALCULATE_RESERVE_GMR_VAT: 'Calculate Reserve GMR/VAT',
  CALCULATE_RESERVE_TRANSACTION_ALLOCATION: 'Calculate Reserve Transaction Allocation',
  CALCULATE_SETTLEMENT: 'Calculate Settlement',

  FINALIZE_LINE_RENTAL: 'Finalize Line Rental',
  FINALIZE_SETTLEMENT: 'Finalize Settlement',

  GENERATE_ENERGY_BILLING_STATEMENT: 'Generate Energy Billing Statement',
  GENERATE_ENERGY_FILES: 'Generate Energy Files',
  GENERATE_FILES: 'Generate Files',
  GENERATE_LINE_RENTAL_FILES: 'Generate Line Rental Files',
  GENERATE_RESERVE_BILLING_STATEMENT: 'Generate Reserve Billing Statement',
  GENERATE_RESERVE_FILES: 'Generate Reserve Files',
  GENERATE_RESERVE_MONTHLY_SUMMARY: 'Generate Reserve Monthly Summary',
  GENERATE_RESERVE_TRANSACTION_REPORT: 'Generate Reserve Transaction Report',
  GENERATE_TRANSACTION_REPORT: 'Generate Transaction Report',

  PUBLISH_TRANSACTION_REPORT: 'Publish Transaction Report',

  VALIDATE_INPUT: 'Validate Input',
  VIEW_CALCULATIONS: 'View Calculations',
  VIEW_DAILY_STATUS: 'View Daily Status',
  VIEW_VALIDATIONS: 'View Validations',

  TRADING_START_DATE: 'Trading Start Date',
  TRADING_END_DATE: 'Trading End Date',

  REMARKS: 'Remarks',

  BILLING_PERIOD_TRADING_DATE: 'Billing Period/Trading Date',
  REPORT_CODE: 'Report Code',

  FUEL_TYPE: 'Fuel Type',
  FUEL_TYPES: 'Fuel Types',
  EFFECTIVE_START_DATE: 'Effective Start Date',
  EFFECTIVE_END_DATE: 'Effective End Date',

  MANAGE_SEC_PARAMETERS: 'Manage SEC Parameters',
  SEC_PARAMETER: 'SEC Parameter',
  EFFECTIVE_DATE: 'Effective Date',

  ACTIVE: 'Active',
  INACTIVE: 'Inactive',

  WESM_PENALTY: 'WESM Penalty',
  BILLING_ID: 'Billing ID',
  TYPE: 'Type',
  AMOUNT: 'Amount',
  PENALTY_AMOUNT: 'Penalty Amount',
  DOCUMENT_NUMBER: 'Document Number',
  DATE: 'Date',
  RESOURCE_ID: 'Resource ID',
  PENALTY_OR_REFUND: 'Penalty (or Refund)',

  MORE_ACTIONS: 'More Actions',
  GENERATE_REFUND_IWS: 'Generate Refund IWS',
  GENERATE_PENALTY_IWS: 'Generate Penalty IWS',

  CALCULATE: 'Calculate',
  FINALIZE: 'Finalize',
  SELECTED: 'Selected',

  PRICING_CONDITION: 'Pricing Condition',
  PROGRESS: 'Progress',
  APPROVED_RATE: 'Approved Rate',
  ADDITIONAL_COMPENSATION_CLAIMS: 'Additional Compensation Claims',
  FILE_A_CLAIM: 'File a Claim',

  DATE_RANGE: 'Date Range',
  CLAIMANT: 'Claimant',

  CREATED_DATE: 'Created Date',
  PIPELINES: 'Pipelines',
  DETAILS: 'Details',

  ALLOCATION_DATE: 'Allocation Date',
  ALLOCATION_DUE_DATE: 'Allocation Due Date',
  ALLOCATION_REMARKS: 'Allocation Remarks',

}
