export const MQ_UPLOAD_CATEGORY = {
  DAILY: 'DAILY',
  MONTHLY: 'MONTHLY',
  CORRECTED_METER_DATA_DAILY: 'CORRECTED_METER_DATA_DAILY',
  CORRECTED_METER_DATA_MONTHLY: 'CORRECTED_METER_DATA_MONTHLY',
}

export const MQ_UPLOADER_STATUS = {
  ACCEPTED: 'Accepted',
  REJECTED: 'Rejected'
}