export const MQ_UPLOAD_CATEGORY = {
  DAILY: 'DAILY',
  MONTHLY: 'MONTHLY',
  CORRECTED_DAILY: 'CORRECTED_DAILY',
  CORRECTED_MONTHLY: 'CORRECTED_MONTHLY',
}

export const MQ_UPLOADER_STATUS = {
  ACCEPTED: 'Accepted',
  REJECTED: 'Rejected'
}